;-------------------------------------------------------------------------
; 	RASTER FX FRAMEWORK
;-------------------------------------------------------------------------

;-------------------------------------------------------------------------
; 	OS defines
;-------------------------------------------------------------------------

osfile = $FFDD
oswrch = $FFEE
osasci = $FFE3
osbyte = $FFF4
osword = $FFF1
osfind = $FFCE
osgbpb = $FFD1
osargs = $FFDA
oscli=$fff7

;-------------------------------------------------------------------------

mode2_palette .function index,physical
                .endf (index<<4)|(physical^7)

                ; this produces the left value
mode2_left .function index
                .endf ((index&8)<<4)|((index&4)<<3)|((index&2)<<2)|((index&1)<<1)

mode2_right .function index
                .endf mode2_left(index)>>1

mode2_value .function left,right
                .endf mode2_left(left)|mode2_right(right)

; ; Palette values for ULA
; PAL_black	= (0 ^ 7)
; PAL_blue	= (4 ^ 7)
; PAL_red		= (1 ^ 7)
; PAL_magenta = (5 ^ 7)
; PAL_green	= (2 ^ 7)
; PAL_cyan	= (6 ^ 7)
; PAL_yellow	= (3 ^ 7)
; PAL_white	= (7 ^ 7)

;-------------------------------------------------------------------------

;-------------------------------------------------------------------------
; 	SYSTEM defines
;-------------------------------------------------------------------------

; MODE1_COL0=$00
; MODE1_COL1=$20
; MODE1_COL2=$80
; MODE1_COL3=$A0

;-------------------------------------------------------------------------
; 	MACROS
;-------------------------------------------------------------------------

;-------------------------------------------------------------------------
; 	GLOBAL constants
;-------------------------------------------------------------------------

video_control_value=$f4                 ;mode 2
access_shadow=4
display_shadow=1


video_control=$fe20   
video_palette=$fe21
acccon=$fe34
                
; Default screen address
screen_addr = $3000
SCREEN_SIZE_BYTES = $8000 - screen_addr

; Exact time for a 50Hz frame less latch load time
FramePeriod = 312*64-2

; Calculate here the timer value to interrupt at the desired line
TimerValue = 32*64 - 2*64 - 2 - 20

; 40 lines for vblank
; 32 lines for vsync (vertical position = 35 / 39)
; interupt arrives 2 lines after vsync pulse
; 2 us for latch
; XX us to fire the timer before the start of the scanline so first colour set on column -1
; YY us for code that executes after timer interupt fires

;-------------------------------------------------------------------------
; 	ZERO PAGE
;-------------------------------------------------------------------------

*=$70
                .dsection bss

; System variables

vsync_counter: .fill 2		; counts up with each vsync
escape_pressed: .fill 1         ; set when Escape key pressed
                
; FX variables

fx_colour_index: .fill 1        ; index into our colour palette
row_counter: .fill 1

                .cerror *>=$9f,"ZP overflow"

;-------------------------------------------------------------------------
; 	CODE START
;-------------------------------------------------------------------------

*=$e00
                .dsection code
start:

main_start:

;-------------------------------------------------------------------------
; 	Code entry
;-------------------------------------------------------------------------

main: .proc
; Set interrupts

                sei        ; disable interupts
                lda #$7F   ; A=01111111
                sta $FE4E  ; R14=Interrupt Enable (disable all interrupts)
                sta $FE43 ; R3=Data Direction Register "A" (set keyboard data
                ; direction)
                lda #$C2  ; A=11000010
                sta $FE4E ; R14=Interrupt Enable (enable main_vsync and timer
                ; interrupt)
                cli       ; enable interupts

                ; Load SIDEWAYS RAM modules here!

                ; Initalise system vars

                lda #0
                sta vsync_counter
                sta vsync_counter+1
                sta escape_pressed

                ; Set MODE 1

                lda #22
                jsr oswrch
                lda #2
                jsr oswrch

                ; Turn off cursor

                lda #10
                sta $FE00
                lda #32
                sta $FE01

                ; ; Set Colour 2 to White - MODE 1 requires 4x writes to ULA
                ; ; Palette Register

                ; lda #MODE1_COL2 + PAL_white
                ; sta $FE21
                ; eor #$10
                ; sta $FE21
                ; eor #$40
                ; sta $FE21
                ; eor #$10
                ; sta $FE21

                ; Initialise system modules here!

                ; DEMO START - from here on out there are no interrupts enabled!!

                sei

                jsr fx_kill_function

	; Exact cycle VSYNC by Hexwab

		lda #2
-
		bit $FE4D
		beq -           ; wait for vsync

		;now we're within 10 cycles of vsync having hit

		;delay just less than one frame
syncloop:
		sta $FE4D ; 4(stretched), ack vsync

		;{ this takes (5*ycount+2+4)*xcount cycles
		;x=55,y=142 -> 39902 cycles. one frame=39936
		ldx #142 ;2
deloop:
		ldy #55 ;2
innerloop:
		dey ;2
		bne innerloop ;3
		; =152
		dex ; 2
		bne deloop ;3
		;}

                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop ; +16
                
		bit $FE4D ;4(stretched)
		bne syncloop ; +3
		; 4+39902+16+4+3+3 = 39932
		; ne means vsync has hit
		; loop until it hasn't hit

		;now we're synced to vsync

                ; Set up Timers

set_timers:
                ; Write T1 low now (the timer will not be written
                ; until you write the high byte)
                lda #<TimerValue
                sta $FE44
                
                ; Get high byte ready so we can write it as quickly as
                ; possible at the right moment
                ldx #>TimerValue
                stx $FE45  ; start T1 counting ; 4c +1/2c

                ; Latch T1 to interupt exactly every 50Hz frame
                lda #<FramePeriod
                sta $FE46
                lda #>FramePeriod
                sta $FE47

                ; Initialise FX modules here

call_init:
                jsr fx_init_function

                ; We don't know how long the init took so resync to timer 1

		lda #$42
		sta $FE4D	; clear vsync $ timer 1 flags

		; Wait for Timer1 at rasterline 0

		lda #$40
-
		bit $FE4D
		beq -
		sta $FE4D

		; Now can enter main loop with enough time to do work

                ; Update typically happens during vblank so wait 255 lines
                ; But don't forget that the loop also takes time!!

		ldx #245
-
		jsr cycles_wait_128
		dex
		bne -

                ; MAIN LOOP

main_loop:

                ;  Do useful work during vblank (vsync will occur at
                ;  some point)
		inc vsync_counter
		bne +
		inc vsync_counter+1
+

; Service any system modules here!

; Check for Escape key

                lda #$79
                ldx #($70 ^ $80)
                jsr osbyte
                stx escape_pressed

                ; FX update callback here!

call_update:
                jsr fx_update_function

                ; Wait for first scanline

		lda #$40
-
		bit $FE4D       ; 4c + 1/2c
		beq -         	; poll timer1 flag
		sta $FE4D       ; clear timer1 flag ; 4c +1/2c

                ; Check if Escape pressed

                ; lda escape_pressed
                ; bmi call_kill

                ; FX draw callback here!

call_draw:
                jsr fx_draw_function

                ; Loop as fast as possible

                jmp main_loop

                ; Get current module to return CRTC to known state

call_kill:
                jsr fx_kill_function

                ; Re-enable useful interupts

                lda #$D3        ; A=11010011
                sta $FE4E       ; R14=Interrupt Enable
                cli

                ; Exit gracefully (in theory)

                rts
                .pend

;-------------------------------------------------------------------------
; 	HELPER FUNCTIONS
;-------------------------------------------------------------------------

cycles_wait_128:		; JSR to get here takes 6c
                .rept 58
                nop
                .next
                rts
; {
; 	FOR n,1,58,1		; 58x
; 	NOP					; 2c
; 	NEXT				; = 116c
; 	RTS					; 6c
; }						; = 128c

main_end:

;-------------------------------------------------------------------------
; 	FX MODULE
;-------------------------------------------------------------------------

fx_start:

;-------------------------------------------------------------------------
; Initialise FX
;
; The initialise function is used to set up all variables, tables and
; any precalculated screen memory etc. required for the FX.
;
; This function will be called during vblank
; The CRTC registers will be set to default MODE 0,1,2 values
;
; The function can take as long as is necessary to initialise.
;-------------------------------------------------------------------------

fx_init_function: .proc

                lda #mode2_palette(11,0)
                sta video_palette

                lda #mode2_palette(12,0)
                sta video_palette

                lda #access_shadow
                trb acccon

                ldx #<load_pic
                ldy #>load_pic
                jsr oscli

                lda #access_shadow
                tsb acccon

                lda #mode2_value(5,5)

                stz dest+0
                lda #$30
                sta dest+1

-
dest=*+1
                sta $ffff
                inc dest+0
                bne -
                inc dest+1
                bpl -

                lda #access_shadow
                trb acccon

                lda #mode2_palette(11,11)
                sta video_palette

                lda #mode2_palette(12,12)
                sta video_palette

                rts

load_pic:
                .text "LOAD PIC",13
                .pend

;-------------------------------------------------------------------------
; Update FX
;
; The update function is used to update / tick any variables used
; in the FX. It may also prepare part of the screen buffer before
; drawing commenses but note the strict timing constraints!
;
; This function will be called during vblank, after any system
; modules have been polled.
;
; The function MUST COMPLETE BEFORE TIMER 1 REACHES 0, i.e. before
; raster line 0 begins. If you are late then the draw function will
; be late and your raster timings will be wrong!
;-------------------------------------------------------------------------

fx_update_function: .proc
                ; Increment our index into the palette table
                inc fx_colour_index
                rts
                .pend

;-------------------------------------------------------------------------
; Draw FX
;
; The draw function is the main body of the FX.
;
; This function will be exactly at the start* of raster line 0 with
; a maximum jitter of up to +10 cycles.
;
; This means that a new CRTC cycle has just started! If you didn't
; specify the registers from the previous frame then they will be
; the default MODE 0,1,2 values as per initialisation.
;
; If messing with CRTC registers, THIS FUNCTION MUST ALWAYS PRODUCE
; A FULL AND VALID 312 line PAL signal before exiting!
;-------------------------------------------------------------------------

fx_draw_function: .proc

                ldx #0
                ldy fx_colour_index

                ; shift timing
                .rept 38
                nop
                .next

raster_loop:
                lda video_control_values,y ;4 4
                sta video_control ;4 8

                .rept 56        ;112 120
                nop
                .next
                .byte $03       ;1 121

                dey             ;2 123
                inx             ;2 125
                bne raster_loop ;3 128

                rts                

                .pend

                ;

;                include ".tmp/routines.s65"
                
;-------------------------------------------------------------------------
; Kill FX
;
; The kill function is used to tidy up any craziness that your FX
; might have created and return the system back to the expected
; default state, ready to initialise the next FX.
;
; This function will be exactly at the start* of raster line 0 with
; a maximum jitter of up to +10 cycles.
;
; This means that a new CRTC cycle has just started! If you didn't
; specify the registers from the previous frame then they will be
; the default MODE 0,1,2 values as per initialisation.
;
; THIS FUNCTION MUST ALWAYS ENSURE A FULL AND VALID 312 line PAL
; signal will take place this frame! The easiest way to do this is
; to simply call crtc_reset.
;
;-------------------------------------------------------------------------

fx_kill_function: .proc
                ; Set all CRTC registers back to their defaults for MODE 0,1,2

                ldx #13
loop:
                stx $FE00
                lda crtc_regs_default,x
                sta $FE01
                dex
                bpl loop 

                rts
                .pend

fx_end:

;-------------------------------------------------------------------------
; 	SYSTEM DATA
;-------------------------------------------------------------------------

data_start:

crtc_regs_default:
                .byte 127    ; R0  horizontal total
                .byte 80     ; R1  horizontal displayed
                .byte 98     ; R2  horizontal position
                .byte $28    ; R3  sync width 40 = $28
                .byte 38     ; R4  vertical total
                .byte 0      ; R5  vertical total adjust
                .byte 32     ; R6  vertical displayed
                .byte 35     ; R7  vertical position; 35=top of screen
                .byte $0     ; R8  interlace; $30 = HIDE SCREEN
                .byte 7      ; R9  scanlines per row
                .byte 32     ; R10 cursor start
                .byte 8      ; R11 cursor end
                .byte >(screen_addr/8)	; R12 screen start address, high
                .byte <(screen_addr/8)	; R13 screen start address, low

; osfile_filename:
;                 .text "Screen",13

; osfile_params:
; osfile_nameaddr:
;                 .word osfile_filename
;                 ; file load address
; osfile_loadaddr:
;                 .dword screen_addr
;                 ; file exec address
; osfile_execaddr:
;                 .dword 0
;                 ; start address or length
; osfile_length:
;                 .dword 0
;                 ; end address of attributes
; osfile_endaddr:
;                 .dword 0

;-------------------------------------------------------------------------
; 	FX DATA
;-------------------------------------------------------------------------

                .align $100
video_control_values:
                .for i=0,i<256,i+=1
                .byte video_control_value|((i>>4)&1)
                .next
                
;                 .align $100
; fx_colour1_table:
;                 .rept 43
;                 .byte MODE1_COL1 + PAL_red
;                 .next
;                 .rept 42
;                 .byte MODE1_COL1 + PAL_magenta
;                 .next
;                 .rept 43
;                 .byte MODE1_COL1 + PAL_blue
;                 .next
;                 .rept 43
;                 .byte MODE1_COL1 + PAL_cyan
;                 .next
;                 .rept 43
;                 .byte MODE1_COL1 + PAL_green
;                 .next
;                 .rept 42
;                 .byte MODE1_COL1 + PAL_yellow
;                 .next

; fx_colour2_table:
;                 .rept 21
;                 .byte MODE1_COL3 + PAL_red
;                 .next
;                 .rept 42
;                 .byte MODE1_COL3 + PAL_magenta
;                 .next
;                 .rept 43
;                 .byte MODE1_COL3 + PAL_blue
;                 .next
;                 .rept 43
;                 .byte MODE1_COL3 + PAL_cyan
;                 .next
;                 .rept 43
;                 .byte MODE1_COL3 + PAL_green
;                 .next
;                 .rept 42
;                 .byte MODE1_COL3 + PAL_yellow
;                 .next
;                 .rept 22
;                 .byte MODE1_COL3 + PAL_red
;                 .next

data_end:

;-------------------------------------------------------------------------
; 	End address to be saved
;-------------------------------------------------------------------------

.end

;-------------------------------------------------------------------------
; 	Save the code
;-------------------------------------------------------------------------

; SAVE "MyFX", start, end

;-------------------------------------------------------------------------
; 	Space reserved for runtime buffers not preinitialised
;-------------------------------------------------------------------------

.bss_start
.bss_end

;-------------------------------------------------------------------------
; 	Memory Info
;-------------------------------------------------------------------------

; PRINT "------"
; PRINT "RASTER FX"
; PRINT "------"
; PRINT "MAIN size =", ~main_end-main_start
; PRINT "FX size = ", ~fx_end-fx_start
; PRINT "DATA size =",~data_end-data_start
; PRINT "BSS size =",~bss_end-bss_start
; PRINT "------"
; PRINT "HIGH WATERMARK =", ~P%
; PRINT "FREE =", ~screen_addr-P%
; PRINT "------"

;-------------------------------------------------------------------------
;	Any other files for the disc
;-------------------------------------------------------------------------

; PUTBASIC "circle.bas", "Circle"
; PUTFILE "screen.bin", "Screen", $3000

                .cerror *>=$3000,'overflow into display memory'